#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

public static class CsvSoAutoCreator
{
    // 자동 생성된 SO 스크립트를 저장할 폴더
    const string SoScriptFolder = "Assets/_Scripts/CSVParser/AutoGenerated";

    // CSV를 순회해서 없는 SO 타입만 스크립트 파일로 생성
    public static int EnsureMissingSoScripts()
    {
        EnsureFolder(SoScriptFolder);

        var csvPaths = CsvImportUtil.FindCsvPaths();
        int created = 0;

        for (int i = 0; i < csvPaths.Length; i++)
        {
            string tableName = Path.GetFileNameWithoutExtension(csvPaths[i]);

            if (HasSoType(tableName))
            {
                continue;
            }

            string scriptPath = $"{SoScriptFolder}/{tableName}SO.cs";
            string script = BuildScript(tableName, csvPaths[i]);
            File.WriteAllText(Path.GetFullPath(scriptPath), script, new UTF8Encoding(false));
            created++;
            Debug.Log($"[CsvSoAutoCreator] Created: {scriptPath}");
        }

        AssetDatabase.Refresh();
        return created;
    }

    // 이미 프로젝트에 {TableName}SO 타입이 있으면 생성 대상에서 제외
    static bool HasSoType(string tableName)
        => TypeCache.GetTypesDerivedFrom<ScriptableObject>()
            .Any(type => type.Name == $"{tableName}SO");

    // CSV 헤더/타입행을 읽어 Row + SO 클래스 코드 문자열을 생성
    static string BuildScript(string tableName, string csvPath)
    {
        var lines = CsvImportUtil.SplitLines(File.ReadAllText(Path.GetFullPath(csvPath)));
        var header = lines.Count > 0 ? CsvImportUtil.SplitCsvLine(lines[0]) : new List<string>();
        var typeLine = lines.Count > 1 ? CsvImportUtil.SplitCsvLine(lines[1]) : new List<string>();
        bool hasTypeLine = CsvImportUtil.IsTypeDefinitionRow(typeLine);

        string rowTypeName = BuildRowTypeName(tableName);
        string soTypeName = $"{tableName}SO";
        string menuName = SplitPascal(tableName);
        var fields = BuildFields(header, hasTypeLine ? typeLine : null);

        var sb = new StringBuilder(1024);
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine();
        sb.AppendLine("[Serializable]");
        sb.AppendLine($"public sealed class {rowTypeName}");
        sb.AppendLine("{");
        for (int i = 0; i < fields.Count; i++)
            sb.AppendLine($"    public {fields[i].Type} {fields[i].Name};");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine($"[CreateAssetMenu(menuName = \"Game/Data/{menuName}\", fileName = \"SO_{tableName}\")]");
        sb.AppendLine($"public sealed class {soTypeName} : ScriptableObject");
        sb.AppendLine("{");
        sb.AppendLine($"    [SerializeField] private List<{rowTypeName}> _rows = new();");
        sb.AppendLine();
        sb.AppendLine($"    public IReadOnlyList<{rowTypeName}> Rows => _rows;");
        sb.AppendLine();
        sb.AppendLine("#if UNITY_EDITOR");
        sb.AppendLine($"    public void ReplaceAll(List<{rowTypeName}> newRows)");
        sb.AppendLine("    {");
        sb.AppendLine($"        _rows = newRows ?? new List<{rowTypeName}>();");
        sb.AppendLine("    }");
        sb.AppendLine("#endif");
        sb.AppendLine("}");
        return sb.ToString();
    }

    // 헤더와 타입행을 기준으로 C# field 목록을 구성
    static List<FieldDef> BuildFields(List<string> header, List<string> typeLine)
    {
        var fields = new List<FieldDef>(header.Count);
        var used = new HashSet<string>(StringComparer.Ordinal);

        for (int i = 0; i < header.Count; i++)
        {
            string baseName = ToCamelIdentifier(header[i]);
            if (string.IsNullOrEmpty(baseName))
                baseName = $"col{i + 1}";

            string name = EnsureUnique(baseName, used);
            string typeToken = typeLine != null && i < typeLine.Count ? typeLine[i] : "string";
            fields.Add(new FieldDef(MapType(typeToken), name));
        }

        return fields;
    }

    // Table 접미사를 Row로 바꿔 Row 타입명을 생성
    static string BuildRowTypeName(string tableName)
    {
        if (tableName.EndsWith("Table", StringComparison.Ordinal))
            return $"{tableName.Substring(0, tableName.Length - 5)}Row";
        return $"{tableName}Row";
    }

    // CSV 타입 토큰을 기본 C# 타입으로 단순 매핑
    static string MapType(string csvType)
    {
        switch (Normalize(csvType))
        {
            case "bool":
            case "boolean":
                return "bool";
            case "int":
            case "integer":
            case "number":
            case "long":
            case "short":
            case "byte":
                return "int";
            case "float":
            case "double":
            case "decimal":
                return "float";
            default:
                return "string";
        }
    }

    // CSV 컬럼명을 camelCase C# 식별자로 변환
    static string ToCamelIdentifier(string source)
    {
        if (string.IsNullOrWhiteSpace(source))
            return "";

        var tokens = new List<string>();
        var token = new StringBuilder(source.Length);

        for (int i = 0; i < source.Length; i++)
        {
            char c = source[i];
            if (char.IsLetterOrDigit(c))
            {
                token.Append(c);
                continue;
            }

            if (token.Length > 0)
            {
                tokens.Add(token.ToString());
                token.Clear();
            }
        }

        if (token.Length > 0)
            tokens.Add(token.ToString());
        if (tokens.Count == 0)
            return "";

        var sb = new StringBuilder(source.Length);
        for (int i = 0; i < tokens.Count; i++)
        {
            string t = tokens[i];
            if (i == 0)
                sb.Append(char.ToLowerInvariant(t[0])).Append(t.Substring(1));
            else
                sb.Append(char.ToUpperInvariant(t[0])).Append(t.Substring(1));
        }

        string name = sb.ToString();
        if (char.IsDigit(name[0]))
            name = $"_{name}";

        if (CsKeywords.Contains(name))
            name = $"@{name}";

        return name;
    }

    // 중복 필드명이 생기면 숫자 접미사를 붙여 고유화
    static string EnsureUnique(string baseName, HashSet<string> used)
    {
        if (used.Add(baseName))
            return baseName;

        int suffix = 2;
        while (!used.Add($"{baseName}{suffix}"))
            suffix++;
        return $"{baseName}{suffix}";
    }

    // 테이블명을 CreateAssetMenu 표시용 문구로 분리
    static string SplitPascal(string text)
    {
        if (string.IsNullOrEmpty(text))
            return text;

        var sb = new StringBuilder(text.Length + 8);
        sb.Append(text[0]);

        for (int i = 1; i < text.Length; i++)
        {
            char c = text[i];
            char p = text[i - 1];
            if (char.IsUpper(c) && (char.IsLower(p) || char.IsDigit(p)))
                sb.Append(' ');
            sb.Append(c);
        }

        return sb.ToString();
    }

    // 타입 판별용 문자열 비교를 위해 영숫자 소문자 형태로 정규화
    static string Normalize(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
            return "";

        var sb = new StringBuilder(value.Length);
        for (int i = 0; i < value.Length; i++)
        {
            char c = value[i];
            if (char.IsLetterOrDigit(c))
                sb.Append(char.ToLowerInvariant(c));
        }
        return sb.ToString();
    }

    // 식별자 충돌 방지용 C# 예약어 목록
    static readonly HashSet<string> CsKeywords = new(StringComparer.Ordinal)
    {
        "class", "struct", "enum", "namespace", "event", "operator", "params", "ref", "out", "in",
        "base", "this", "new", "public", "private", "protected", "internal", "static", "readonly",
        "void", "string", "int", "float", "bool", "long", "short", "byte", "double", "decimal"
    };

    // 생성할 field의 타입/이름을 묶는 내부 구조체
    readonly struct FieldDef
    {
        public readonly string Type;
        public readonly string Name;

        public FieldDef(string type, string name)
        {
            Type = type;
            Name = name;
        }
    }

    // 중간 폴더가 없으면 경로를 단계적으로 생성
    static void EnsureFolder(string folderPath)
    {
        if (AssetDatabase.IsValidFolder(folderPath))
            return;

        var parts = folderPath.Split('/');
        string current = parts[0];

        for (int i = 1; i < parts.Length; i++)
        {
            string next = $"{current}/{parts[i]}";
            if (!AssetDatabase.IsValidFolder(next))
                AssetDatabase.CreateFolder(current, parts[i]);
            current = next;
        }
    }
}

public static class CsvImportCompileBridge
{
    // 스크립트 생성 후 컴파일 완료 시 ImportAll을 자동 재개하기 위한 세션 키
    private const string PendingImportAllKey = "CsvImportCompileBridge.PendingImportAll";

    // SO 스크립트 생성이 필요한 경우 ImportAll을 컴파일 이후로 자동 이연
    public static bool EnsureSoScriptsReadyAndMaybeDefer(string reason)
    {
        int created = CsvSoAutoCreator.EnsureMissingSoScripts();
        if (created <= 0)
            return true;

        QueueImportAllAfterCompile(created, reason);
        return false;
    }

    // 컴파일 후 자동 재개하도록 플래그를 저장하고 안내 팝업을 표시
    public static void QueueImportAllAfterCompile(int createdCount, string reason)
    {
        SessionState.SetBool(PendingImportAllKey, true);

        string safeReason = string.IsNullOrWhiteSpace(reason) ? "CSV Import" : reason;
        EditorUtility.DisplayDialog(
            "CSV Import Deferred",
            $"{safeReason}\n\n{createdCount} new SO scripts were generated.\nAfter script compile, CSV import will resume automatically.",
            "OK"
        );
    }

    // 도메인 리로드 이후 대기 중인 ImportAll 작업을 자동 실행
    [InitializeOnLoadMethod]
    static void ResumePendingImportAll()
    {
        EditorApplication.delayCall += () =>
        {
            if (!SessionState.GetBool(PendingImportAllKey, false))
                return;

            SessionState.EraseBool(PendingImportAllKey);
            CsvBatchImporter.ImportAllTables();
        };
    }
}
#endif
